# syntax=docker/dockerfile:1.4

FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /workspace

ARG GIT_BRANCH=""
ARG GIT_COMMIT=""

# Copy POMs first for better layer caching
COPY pom.xml .
COPY core/pom.xml core/pom.xml
COPY receipt-parser/pom.xml receipt-parser/pom.xml
COPY web/pom.xml web/pom.xml

# Download dependencies in a separate layer for caching
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -Pinclude-web -pl web -am -DskipTests dependency:go-offline

# Copy source code
COPY core core
COPY web web

# Generate git properties if provided
RUN echo "Generating git.properties for Cloud Build..."; \
    echo "GIT_BRANCH=${GIT_BRANCH}"; \
    echo "GIT_COMMIT=${GIT_COMMIT}"; \
    if [ -n "${GIT_BRANCH}${GIT_COMMIT}" ]; then \
      mkdir -p web/src/main/resources; \
      SHORT_COMMIT=$(echo "${GIT_COMMIT}" | cut -c1-7); \
      BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%S%z"); \
      PROJECT_VERSION=$(grep -A 5 '<artifactId>pklnd</artifactId>' pom.xml | grep -oP '<version>\K[^<]+' | head -1); \
      echo "Extracted PROJECT_VERSION=${PROJECT_VERSION}"; \
      { \
        echo "#Generated by Dockerfile build"; \
        if [ -n "${GIT_BRANCH}" ]; then echo "git.branch=${GIT_BRANCH}"; fi; \
        if [ -n "${GIT_COMMIT}" ]; then \
          echo "git.commit.id=${GIT_COMMIT}"; \
          echo "git.commit.id.abbrev=${SHORT_COMMIT}"; \
        fi; \
        echo "git.build.time=${BUILD_TIME}"; \
        echo "git.build.version=${PROJECT_VERSION}"; \
      } > web/src/main/resources/git.properties; \
      echo "Created git.properties:"; \
      cat web/src/main/resources/git.properties; \
    else \
      echo "WARNING: GIT_BRANCH and GIT_COMMIT are empty, not generating git.properties"; \
    fi

# Build the application with Maven cache mount, skipping git-commit-id-plugin
RUN --mount=type=cache,target=/root/.m2 \
    mvn -B -Pinclude-web -pl web -am -DskipTests -Dgit-commit-id-plugin.skip=true package \
    && JAR_PATH="$(find web/target -maxdepth 1 -type f -name '*-SNAPSHOT.jar' ! -name '*original*' | head -n 1)" \
    && cp "${JAR_PATH}" /workspace/app.jar \
    && echo "Verifying git.properties in JAR:" \
    && unzip -p /workspace/app.jar BOOT-INF/classes/git.properties || echo "WARNING: git.properties not found in JAR!"

FROM eclipse-temurin:21-jre

ENV JAVA_OPTS=""
WORKDIR /app

COPY --from=build /workspace/app.jar app.jar

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/app.jar"]
