[[build.env]]
name = "GOOGLE_BUILDABLE"
value = "function"

[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "21"

[[build.env]]
name = "MAVEN_BUILD_ARGUMENTS"
value = "-pl function -am -DskipTests package"
