[[build.env]]
name = "BP_NATIVE_IMAGE"
value = "true"

[[build.env]]
name = "BP_JVM_VERSION"
value = "21"

[[build.env]]
name = "BP_MAVEN_BUILD_ARGUMENTS"
value = "-pl function -am -DskipTests clean install"

