[[build.env]]
name = "GOOGLE_BUILDABLE"
value = "receipt-parser"

[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "21"

[[build.env]]
name = "MAVEN_BUILD_ARGUMENTS"
value = "-pl receipt-parser -am -DskipTests package"
