spring:
  application:
    name: ResponsiveAuthApp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
  cloud:
    function:
      definition: receiptProcessingFunction
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${VERTEX_AI_PROJECT_ID:codex-test-473008}
          location: ${VERTEX_AI_LOCATION:us-central1}
          model: ${VERTEX_AI_GEMINI_MODEL:gemini-2.0-flash}
          chat:
            options:
              model: ${VERTEX_AI_GEMINI_MODEL:gemini-2.0-flash}

logging:
  level:
    root: INFO
    dev.pekelund.responsiveauth.function: INFO
    org.springframework.ai: INFO

server:
  error:
    whitelabel:
      enabled: false

firestore:
  enabled: ${FIRESTORE_ENABLED:false}
  credentials: ${FIRESTORE_CREDENTIALS:}
  project-id: ${FIRESTORE_PROJECT_ID:}
  users-collection: ${FIRESTORE_USERS_COLLECTION:users}
  default-role: ${FIRESTORE_DEFAULT_ROLE:ROLE_USER}

gcs:
  enabled: ${GCS_ENABLED:false}
  credentials: ${GCS_CREDENTIALS:}
  project-id: ${GCS_PROJECT_ID:}
  bucket: ${GCS_BUCKET:}
