spring:
  application:
    name: responsive-auth-web
  messages:
    basename: messages
    fallback-to-system-locale: false

server:
  forward-headers-strategy: framework

firestore:
  enabled: ${FIRESTORE_ENABLED:false}
  credentials: ${FIRESTORE_CREDENTIALS:}
  project-id: ${FIRESTORE_PROJECT_ID:}
  emulator-host: ${FIRESTORE_EMULATOR_HOST:}
  users-collection: ${FIRESTORE_USERS_COLLECTION:users}
  receipts-collection: ${RECEIPT_FIRESTORE_COLLECTION:receiptExtractions}
  default-role: ${FIRESTORE_DEFAULT_ROLE:ROLE_USER}

gcs:
  enabled: ${GCS_ENABLED:false}
  credentials: ${GCS_CREDENTIALS:}
  project-id: ${GCS_PROJECT_ID:}
  bucket: ${GCS_BUCKET:}

receipt-processor:
  base-url: ${RECEIPT_PROCESSOR_BASE_URL:}
  audience: ${RECEIPT_PROCESSOR_AUDIENCE:}

