spring:
  application:
    name: responsive-auth-web
  messages:
    basename: messages
    fallback-to-system-locale: false

server:
  forward-headers-strategy: framework

firestore:
  enabled: ${FIRESTORE_ENABLED:false}
  credentials: ${FIRESTORE_CREDENTIALS:}
  project-id: ${FIRESTORE_PROJECT_ID:${PROJECT_ID:}}
  emulator-host: ${FIRESTORE_EMULATOR_HOST:}
  users-collection: ${FIRESTORE_USERS_COLLECTION:users}
  receipts-collection: ${RECEIPT_FIRESTORE_COLLECTION:receiptExtractions}
  receipt-items-collection: ${RECEIPT_FIRESTORE_ITEM_COLLECTION:receiptItems}
  item-stats-collection: ${RECEIPT_FIRESTORE_ITEM_STATS_COLLECTION:receiptItemStats}
  default-role: ${FIRESTORE_DEFAULT_ROLE:ROLE_USER}

gcs:
  enabled: ${GCS_ENABLED:false}
  credentials: ${GCS_CREDENTIALS:}
  project-id: ${GCS_PROJECT_ID:${PROJECT_ID:}}
  bucket: ${GCS_BUCKET:}

receipt:
  processing:
    enabled: ${RECEIPT_PROCESSOR_ENABLED:true}
    base-url: ${RECEIPT_PROCESSOR_BASE_URL:}
    event-path: ${RECEIPT_PROCESSOR_EVENT_PATH:/events/storage}
    use-id-token: ${RECEIPT_PROCESSOR_USE_ID_TOKEN:true}
    audience: ${RECEIPT_PROCESSOR_AUDIENCE:}
    connect-timeout: ${RECEIPT_PROCESSOR_CONNECT_TIMEOUT:5s}
    read-timeout: ${RECEIPT_PROCESSOR_READ_TIMEOUT:30s}

