spring:
  application:
    name: receipt-processing-service

google:
  ai:
    gemini:
      model: ${GOOGLE_AI_GEMINI_MODEL:gemini-2.0-flash}

logging:
  level:
    root: INFO
    dev.pekelund.pklnd.receiptparser: INFO
    org.springframework.ai: INFO

server:
  port: ${PORT:8080}

app:
  logging:
    project-id: ${LOGGING_PROJECT_ID:${GOOGLE_CLOUD_PROJECT:${GCP_PROJECT:${PROJECT_ID:codex-test-473008}}}}
    log-name: ${LOGGING_LOG_NAME:${spring.application.name}}
