options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--file'
      - '${_DOCKERFILE}'
      - '--tag'
      - '${_IMAGE_URI}'
      - '--cache-from'
      - '${_IMAGE_URI}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - '${_IMAGE_URI}'
      - '${_IMAGE_URI}:latest'

images:
  - '${_IMAGE_URI}'
  - '${_IMAGE_URI}:latest'
